name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v4
    - name : Install mingw-w64
      run: sudo apt update && sudo apt install mingw-w64
    - name: Create the resource.rc
      run: touch resource.rc
    - name: Edit the resource.rc
      run: echo '1 ICON "app.ico"' > resource.rc
    - name: Make the resource.res
      run: x86_64-w64-mingw32-windres resource.rc -O coff -o resource.res
    - name: Compile the kusa.c
      run: x86_64-w64-mingw32-gcc kusa.c resource.res -o kusa.exe
    - name: Compile the KusaFuckUpdater.c
      run: x86_64-w64-mingw32-gcc KusaFuckUpdater.c resource.res -o KusaFuckUpdater.exe -I./include -L./lib -lcurl

